[package]
name = "part1"
version = "0.1.0"
authors = ["Tyler Marshall <tyler.e.marshall@raytheon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "2.0.1"
crossterm = "0.14.0"